from datetime import datetime
from recommonmark.transform import AutoStructify
# -- Project information -----------------------------------------------------
gitlab_doc_root = 'https://gitlab.com/CinCan/cincan-command/-/tree/docs/docs'

project = u'CinCan Command'

year = datetime.now().year
project_name = "CinCan Project"
href = f'<a href="https://cincan.io">{project_name}</a>'
copyright = f"{year} {href}"


# The full version, including alpha/beta/rc tags
release = 'https://gitlab.com/cincan/cincan-command'

master_doc = "index"

html_theme_options = {
    "description": "A convenient way to run dockerized command-line tools.",
    # "fixed_sidebar": True,
    "logo": "cincan-command.png",
    "logo_name": True,
    "logo_text_align": "left",
    "extra_nav_links": {'CinCan repository': 'https://gitlab.com/CinCan/cincan-command'},
}

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['recommonmark', 'sphinx.ext.autosectionlabel', 'sphinx.ext.viewcode']
source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}
# Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', ]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'
html_sidebars = {
    '**': [
        # 'navigation.html'
        'about.html',
        'sourcelink.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
    ]
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# Page source url
html_show_sourcelink = False
# Powered by
show_powered_by = False
html_show_sphinx = False
# Copyright
html_show_copyright = True

def setup(app):
    app.add_config_value('recommonmark_config', {
            'url_resolver': lambda url: gitlab_doc_root + url,
            'auto_toc_tree_section': 'Contents',
            }, True)
    app.add_transform(AutoStructify)
